name: NuGet Push
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4     
        with:
            dotnet-version: '8.0.x'  
      - name: Install .NET Aspire workload
        run: dotnet workload install aspire
      - name: Build and Publish
        run: |  
          cd ./src/ClickHouse.Hosting/
          dotnet pack -c Release -o artifacts -p:PackageVersion=1.1.0
      - name: Push
        run: dotnet nuget push ./src/ClickHouse.Hosting/artifacts/ClickHouse.Hosting.1.1.0.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json